import type { Metadata } from "next";
import "@/app/globals.css";
import "./auth.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="auth-layout">
          <div className="background-image blur-sm"></div>
          <div className="content">{children}</div>
        </div>
      </body>
    </html>
  );
}
