import type { Metadata } from 'next';
import './auth.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="background-image blur-sm"></div>
      <div className="content">{children}</div>
    </>
  );
}
